class element ():
    base_url = "https://www.saucedemo.com/"
    username = "user-name"
    password ="password"
    add_chart = "add-to-cart-sauce-labs-backpack"
    btn_login ="login-button"
    title = "title"
    required_password ="//*[@id='login_button_container']/div/form/div[3]/h3"
    required_username = "//*[@id='login_button_container']/div/form/div[3]/h3"
    invalid_button = "//*[@id='login_button_container']/div/form/div[3]/h3"
    shopping_cart="shopping_cart_link"
    first_product ="item_4_title_link"
    title_product = "//*[@id='inventory_item_container']/div/div/div[2]/div[1]"
    number_cart = "//*[@id='shopping_cart_container']/a/span"
    remove_button ="remove-sauce-labs-backpack"
    remove_bike_light = "remove-sauce-labs-bike-light"
    bike_light = "add-to-cart-sauce-labs-bike-light"
    t_shirt = "add-to-cart-sauce-labs-bolt-t-shirt"
    btn_cart ="//*[@id='shopping_cart_container']/a"
    header_cart ="//*[@id='header_container']/div[2]/span"
    btn_checkout = "checkout"
    btn_continue = "//*[@id='header_container']/div[2]/span"
    header_overview ="//*[@id='header_container']/div[2]/span"
    btn_finish = "finish"
    header_complete = "//*[@id='header_container']/div[2]/span"
    btn_back_to_home = "back-to-products"
    btn_menu = "react-burger-menu-btn"
    btn_logout = "logout_sidebar_link"

